package com.lvjc.mapper;

import com.lvjc.model.ProjectDataLocker;
import com.lvjc.model.ProjectDataLockerExample;
import com.lvjc.model.ProjectDataLockerKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ProjectDataLockerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bim5d_project_data_locker
     *
     * @mbggenerated
     */
    int countByExample(ProjectDataLockerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bim5d_project_data_locker
     *
     * @mbggenerated
     */
    int deleteByExample(ProjectDataLockerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bim5d_project_data_locker
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(ProjectDataLockerKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bim5d_project_data_locker
     *
     * @mbggenerated
     */
    int insert(ProjectDataLocker record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bim5d_project_data_locker
     *
     * @mbggenerated
     */
    int insertSelective(ProjectDataLocker record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bim5d_project_data_locker
     *
     * @mbggenerated
     */
    List<ProjectDataLocker> selectByExample(ProjectDataLockerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bim5d_project_data_locker
     *
     * @mbggenerated
     */
    ProjectDataLocker selectByPrimaryKey(ProjectDataLockerKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bim5d_project_data_locker
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") ProjectDataLocker record, @Param("example") ProjectDataLockerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bim5d_project_data_locker
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") ProjectDataLocker record, @Param("example") ProjectDataLockerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bim5d_project_data_locker
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ProjectDataLocker record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bim5d_project_data_locker
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ProjectDataLocker record);
}