package com.lvjc.model;

import java.util.Date;

public class ProjectDataLocker extends ProjectDataLockerKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bim5d_project_data_locker.data_type
     *
     * @mbggenerated
     */
    private String dataType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bim5d_project_data_locker.locked_time
     *
     * @mbggenerated
     */
    private Date lockedTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bim5d_project_data_locker.data_type
     *
     * @return the value of bim5d_project_data_locker.data_type
     *
     * @mbggenerated
     */
    public String getDataType() {
        return dataType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bim5d_project_data_locker.data_type
     *
     * @param dataType the value for bim5d_project_data_locker.data_type
     *
     * @mbggenerated
     */
    public void setDataType(String dataType) {
        this.dataType = dataType == null ? null : dataType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bim5d_project_data_locker.locked_time
     *
     * @return the value of bim5d_project_data_locker.locked_time
     *
     * @mbggenerated
     */
    public Date getLockedTime() {
        return lockedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bim5d_project_data_locker.locked_time
     *
     * @param lockedTime the value for bim5d_project_data_locker.locked_time
     *
     * @mbggenerated
     */
    public void setLockedTime(Date lockedTime) {
        this.lockedTime = lockedTime;
    }
}