# DATASOURCE
spring:
  datasource:
    url: jdbc:mysql://localhost/account-book?useUnicode=true&characterEncoding=UTF-8
    username: account-book
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  view:
    prefix: /WEB-INF/views/
    suffix: .jsp
