spring:
  application:
    name: eureka-server:1000
---
server:
  port: 1000
---
eureka:
  instance:
    hostname: localhost
  client:
#    serviceUrl:
#      defaultZone: localhost:1111/eureka
    register-with-eureka: false
    fetch-registry: false
